To-do-App/src/todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from todo_list import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list.urls'))
]

To-do-App/src/todo_list/urls.py
from django.urls import path
from . import views


app_name = 'todo-app'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('delete/(?<id>\d+)/', views.delete, name='delete'),
    path('cross_off/(?<id>\d+)/', views.cross_off, name='cross_off'),
    path('uncross/(?<id>\d+)/', views.uncross, name='uncross'),
    path('edit/(?<id>\d+)/', views.edit, name='edit'),
]

To-do-App/src/todo_list/models.py
from django.db import models

# Create your models here.
class List(models.Model):
	item = models.CharField(max_length=200)
	completed = models.BooleanField(default=False)


	def __str__(self):
		return self.item

To-do-App/src/todo_list/forms.py
from django import forms
from .models import List


class ListForm(forms.ModelForm):
	class Meta:
		model = List
		fields = ['item', 'completed']

To-do-App/src/todo_list/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import List
from .forms import ListForm
# Create your views here.
def home(request):

	if request.method == 'POST':
		form = ListForm(request.POST or None)
		if form.is_valid():
			form.save()
			messages.success(request, ('Item has been Added To List!'))
			all_items = List.objects.all()
			return render(request, 'home.html', {'all_items': all_items})
	else:

		all_items = List.objects.all()
		return render(request, 'home.html', {'all_items': all_items})


def about(request):
	return render(request, 'about.html', {'name': 'Ibrar Butt'})


def delete(request, id):
	item = get_object_or_404(List, pk=id)
	item.delete()
	messages.success(request, ('Item has been deleted From List!'))
	return redirect('todo-app:home')

def cross_off(request, id):
	item = get_object_or_404(List, pk=id)
	item.completed = True
	item.save()
	return redirect('todo-app:home')


def uncross(request, id):
	item = get_object_or_404(List, pk=id)
	item.completed = False
	item.save()
	return redirect('todo-app:home')



def edit(request, id):

	if request.method == 'POST':
		item = get_object_or_404(List, pk=id)
		form = ListForm(request.POST or None, instance=item)
		if form.is_valid():
			form.save()
			messages.success(request, ('Item has been Edited To List!'))
			
			return redirect('todo-app:home')
	else:

		item = get_object_or_404(List, pk=id)
		return render(request, 'edit.html', {'item': item})

To-do-App/src/todo_list/templates/about.html
{% extends 'base.html' %}


{% block title %} To-Do List {% endblock %}

{% block content %}
	<h1>Hello, {{name}}</h1>
	<h2>Welcome to the About page</h2>

{% endblock %}

To-do-App/src/todo_list/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
	  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'todo-app:home' %}">To-Do List</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'todo-app:about' %}">About</a>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0" method="POST">
	    	{% csrf_token %}
	      <input class="form-control mr-sm-2" type="search" placeholder="To-Do Item" aria-label="Search" name="item">
	      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add To List</button>
	    </form>
	  </div>
	</nav>
	<br>
    <div class="container">
		{% block content %}
		{% endblock %}
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

To-do-App/src/todo_list/templates/edit.html
{% extends 'base.html' %}


{% block title %} To-Do List | Edit Item{% endblock %}

{% block content %}

		 <form class="form-inline my-2 my-lg-0" method="POST">
	    	{% csrf_token %}
	     	<input class="form-control mr-sm-2" type="search" placeholder="{{item.item}}" aria-label="Search" value="{{item.item}}" name="item">
	     	<input type="hidden" value="{{item.completed}}" name="completed">
	     	<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Edit Item</button>
	    </form>

{% endblock %}

To-do-App/src/todo_list/templates/home.html
{% extends 'base.html' %}


{% block title %} To-Do List {% endblock %}

{% block content %}

	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-warning alert-dismissable" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert">
					<small><sup>&times;</sup></small>
				</button>
			</div>
			
		{% endfor %}

	{% endif %}


	{% if all_items %}
		<table class="table table-bordered">
			{% for item in all_items %}
				{% if item.completed %}
					<tr class="table-secondary">
						<td class="striker"><a href="{% url 'todo-app:edit' item.id %}">{{item.item}}</a></td>
						<td><center><a href="{% url 'todo-app:uncross' item.id %}">Uncross</a></center></td>
						<td><center><a href="{% url 'todo-app:delete' item.id %}">Delete</a></center></td>
					</tr>
				{% else %}
					<tr>
						<td><a href="{% url 'todo-app:edit' item.id %}">{{item.item}}</a></td>
						<td><center><a href="{% url 'todo-app:cross_off' item.id %}">Cross-off</a></center></td>
						<td><center><a href="{% url 'todo-app:delete' item.id %}">Delete</a></center></td>
					</tr>
				{% endif %}
			{% endfor %}
		</table>
	{% endif %}

{% endblock %}